version: 1
metadata:
  name: Authenticator Validator Stage - Default
context:
  last_auth_threshold: minutes=5
  not_configured_action: skip
  device_classes_map: # class_type: stage_name
    totp: default-totp-authenticator-setup-stage
entries:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Flow - Default TOTP Authenticator Setup
    required: true
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_stages_authenticator_validate.authenticatorvalidatestage
  id: default-authenticator-validator-stage
  identifiers:
    name: default-authenticator-validator-stage
  attrs:
    last_auth_threshold: !Context last_auth_threshold
    configuration_stages: !Enumerate [
      !Context device_classes_map,
      SEQ,
      !Find [
        !Format [authentik_stages_authenticator_%s.authenticator%sstage, !Index 0, !Index 0],
        [name, !Value 0]
      ]
    ]
    device_classes: !Enumerate [
      !Context device_classes_map,
      SEQ,
      !Index 0
    ]
    not_configured_action: !Context not_configured_action
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#