version: 1
metadata:
  name: Flow - Default User Settings
context:
  name: User settings
  title: User settings
entries:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Prompt Stage - User Settings
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Expression Policy - Validate email Context Attribute Is Different Than Currently Set
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Email Stage - Default Confirmation
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: User Write Stage - Default
    required: true
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_flows.flow
  id: flow
  identifiers:
    slug: default-user-settings-flow
  attrs:
    authentication: require_authenticated
    denied_action: continue
    designation: stage_configuration
    name: !Context name
    title: !Context title
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_flows.flowstagebinding
  identifiers:
    stage: !Find [authentik_stages_prompt.promptstage, [name, user-settings-prompt-stage]]
    target: !KeyOf flow
  attrs:
    order: 100

- model: authentik_flows.flowstagebinding
  id: default-user-settings-defaul-confirmation-email-stage-binding
  identifiers:
    stage: !Find [authentik_stages_email.emailstage, [name, default-confirmation-email-stage]]
    target: !KeyOf flow
  attrs:
    order: 200
    re_evaluate_policies: true

- model: authentik_flows.flowstagebinding
  identifiers:
    stage: !Find [authentik_stages_user_write.userwritestage, [name, default-user-write-stage]]
    target: !KeyOf flow
  attrs:
    order: 900
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_policies.policybinding
  identifiers:
    policy: !Find [authentik_policies_expression.expressionpolicy, [name, validate-email-context-attribute-is-different-than-currently-set-expression-policy]]
    target: !KeyOf default-user-settings-defaul-confirmation-email-stage-binding
  attrs:
    order: 0
    enabled: true
    negate: false
    timeout: 30
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
