version: 1
metadata:
  name: Tenant - Default
context:
    fqdn: authentik - default
    branding_title: authentik
    global_attributes:
      goauthentik.io/user/can-change-name: true
      goauthentik.io/user/can-change-username: true
      goauthentik.io/user/can-change-email: true
      better-blueprints/user/name-regex: >-
        ^[a-zA-Z]{2,20}$
      better-blueprints/user/name-validation-error-message: >-
        Names must contain only alphabetic characters and be between 2 and 20
        characters long
      better-blueprints/user/password-regex: >-
        ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$
      better-blueprints/user/password-validation-error-message: >-
        Passwords must consist of minimum eight characters, at least one
        uppercase letter, at least one lowercase letter and at least one number
entries:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Flow - Default Authentication
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Flow - Default Invalidation
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Flow - Default User Settings
    required: true
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_tenants.tenant
  identifiers:
    default: True
  attrs:
    domain: !Context fqdn
    branding_title: !Context branding_title
    flow_authentication: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
    flow_invalidation: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
    flow_user_settings: !Find [authentik_flows.flow, [slug, default-user-settings-flow]]
    attributes: !Context global_attributes
