version: 1
metadata:
  name: Prompt Stage - User Settings
context: {}
entries:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Prompt - username Without Duplicate Check
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Prompt - first_name and last_name
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Prompt - email
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Prompt - attributes.settings.locale
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Expression Policy - Validate Username Email and Name Change Is Allowed
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Expression Policy - Create name Context Attribute From first_name and last_name Context Attributes
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Expression Policy - Validate username Context Attribute Is Unique to Current User
    required: true

- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Expression Policy - Validate email Context Attribute Is Unique to Current User
    required: true
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_stages_prompt.promptstage
  id: user-settings-prompt-stage
  identifiers:
    name: user-settings-prompt-stage
  attrs:
    fields:
    - !Find [authentik_stages_prompt.prompt, [field_key, username], [type, text]]
    - !Find [authentik_stages_prompt.prompt, [field_key, first_name]]
    - !Find [authentik_stages_prompt.prompt, [field_key, last_name]]
    - !Find [authentik_stages_prompt.prompt, [field_key, email]]
    - !Find [authentik_stages_prompt.prompt, [field_key, attributes.settings.locale]]
    validation_policies:
    - !Find [authentik_policies_expression.expressionpolicy, [name, validate-username-email-and-name-change-is-allowed-expression-policy]]
    - !Find [authentik_policies_expression.expressionpolicy, [name, create-name-context-attribute-from-first_name-and-last_name-context-attributes-expression-policy]]
    - !Find [authentik_policies_expression.expressionpolicy, [name, validate-username-context-attribute-is-unique-to-current-user-expression-policy]]
    - !Find [authentik_policies_expression.expressionpolicy, [name, validate-email-context-attribute-is-unique-to-current-user-expression-policy]]
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
