version: 1
metadata:
  name: Password Policy - Default
context:
  password_field: password
  check_have_i_been_pwned: true
  hibp_allowed_count: 1
  check_zxcvbn: true
  zxcvbn_score_threshold: 3
  check_static_rules: true
  amount_digits: 0
  amount_uppercase: 1
  amount_lowercase: 1
  amount_symbols: 1
  length_min: 10
  symbol_charset: >-
    !\"#$%&'()*+,-./:;<=>?@[]^_`{|}~0123456789
  error_message: >-
    Passwords must consist of minimum 10 characters, at least one uppercase
    letter, at least one lowercase letter and at least one digit or special
    character
entries:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Dependency blueprints ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Notification transports ~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Groups ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policies ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
- model: authentik_policies_password.passwordpolicy
  id: default-password-policy
  identifiers:
    name: default-password-policy
  attrs:
    password_field: !Context password_field
    amount_digits: !Context amount_digits
    amount_uppercase: !Context amount_uppercase
    amount_lowercase: !Context amount_lowercase
    amount_symbols: !Context amount_symbols
    length_min: !Context length_min
    symbol_charset: !Context symbol_charset
    error_message: !Context error_message
    check_static_rules: !Context check_static_rules
    check_have_i_been_pwned: !Context check_have_i_been_pwned
    check_zxcvbn: !Context check_zxcvbn
    hibp_allowed_count: !Context hibp_allowed_count
    zxcvbn_score_threshold: !Context zxcvbn_score_threshold
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Flows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Prompts ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stages ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Stage bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Policy bindings ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Tenants ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
